<h1>Fáza 1 - prieskumná analýza

<h2>Základný opis dát spolu s ich charakteristikami
<h3>Uloha 1:

In [7]:
import os
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
import scipy.stats as stats

stations = []
measurements = []


lenght_cf = 0
lenght_df = 0
filename = "data/" + "0"+ str(25) + '/'
        
cf = pd.read_csv(filename+ "measurements.csv",sep ='\t')
measurements = cf
df = pd.read_csv(filename+ "stations.csv",sep ='\t')
stations=df
        
        
   
    #print(cf.shape)
    #print(df.shape)
    #lenght_cf = lenght_cf + len(cf)
    #lenght_df = lenght_df + len(df)
    
measurements

,PM10,NH3,warning,H2CO,SO2,TEMP,C2H3NO5,Pb,NOx,PM2.5,latitude,PRES,longitude,CH4,PAHs,CFCs,CO,O3
0,7.74502,5.66554,1.0,57.03615,10.02018,16.75126,0.04167,40.93202,7.87154,9.92285,52.26083,1182.31351,7.00417,8.53092,6.71732,33.24445,6.57774,10.20087
1,9.00509,8.44381,0.0,55.41733,7.13753,3.92586,0.10191,42.63640,11.34799,8.11740,39.43534,1108.24878,-84.20299,7.42952,5.99743,54.64957,6.76763,9.01290
2,10.15744,4.59693,0.0,63.30345,6.27562,1.85796,0.27831,67.70390,5.44044,8.32536,48.52961,1110.66223,12.16179,7.95468,6.81140,57.81200,8.49049,9.30919
3,6.44879,6.24834,1.0,21.91017,7.57754,17.08684,0.02904,25.35154,6.38345,8.00394,41.00510,1135.61679,-73.78458,7.23988,6.85945,43.24279,6.44554,6.80424
4,14.50236,8.13272,0.0,51.82537,4.81670,8.72152,NaN,37.09306,3.06718,9.16570,61.78491,1076.99556,34.34691,8.58638,8.48867,42.50140,7.16875,7.94615
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12096,6.98324,3.96101,1.0,35.45242,7.77484,15.36379,0.03206,26.39865,5.88455,8.62439,49.41029,1059.07318,38.15035,8.04092,7.81041,30.05312,5.54049,7.15844
12097,6.26488,4.89993,1.0,78.17503,9.70239,1.85992,0.02565,63.52891,5.72752,10.91645,-3.14306,1096.86977,-58.44417,7.21943,9.95392,38.80755,7.78927,6.64297
12098,8.72420,9.15420,0.0,43.03497,7.20861,29.81891,0.08371,28.87521,7.21287,8.77967,43.83125,1124.29627,5.03586,9.34943,6.84354,34.43359,9.57857,6.10178
12099,7.89244,7.18884,0.0,57.25632,7.81167,13.32181,0.03518,36.20571,8.39126,7.28543,10.12268,1107.53766,77.54372,7.64544,6.60066,49.59714,10.21135,9.83768
12100,7.00199,6.91144,1.0,59.68740,9.72734,18.95848,0.03966,33.74588,7.72375,7.86151,45.99194,1145.89906,29.41824,8.18889,8.61029,45.49624,8.52583,7.10253

In [8]:
measurements.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12101 entries, 0 to 12100
Data columns (total 18 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   PM10       12052 non-null  float64
 1   NH3        12050 non-null  float64
 2   warning    12053 non-null  float64
 3   H2CO       12052 non-null  float64
 4   SO2        12052 non-null  float64
 5   TEMP       12053 non-null  float64
 6   C2H3NO5    12053 non-null  float64
 7   Pb         12052 non-null  float64
 8   NOx        12051 non-null  float64
 9   PM2.5      12052 non-null  float64
 10  latitude   12101 non-null  float64
 11  PRES       12101 non-null  float64
 12  longitude  12101 non-null  float64
 13  CH4        12053 non-null  float64
 14  PAHs       12053 non-null  float64
 15  CFCs       12052 non-null  float64
 16  CO         12053 non-null  float64
 17  O3         12051 non-null  float64
dtypes: float64(18)
memory usage: 1.7 MB

In [3]:
stations

,location,revision,longitude,QoS,code,latitude
0,Asia/Manila,"08/11/2021, 00:00:00",120.89694,excellent,PH,14.95472
1,Europe/Paris,11 Mar 2020,2.12213,accep,FR,48.82220
2,Europe/Istanbul,2022/07/03,42.85693,accep,TR,39.22493
3,Asia/Tokyo,2015/08/20,136.84186,average,JP,34.48330
4,Asia/Shanghai,02 Mar 2019,117.65694,average,CN,36.19278
...,...,...,...,...,...,...
1073,Asia/Taipei,"01/27/2019, 00:00:00",119.58627,good,TW,23.56540
1074,Asia/Shanghai,2014-02-20,122.74754,average,CN,40.85158
1075,Europe/Berlin,2018-05-01,8.86704,accep,DE,50.23805
1076,Asia/Colombo,2016-04-12,79.88300,average,LK,6.99090
1077,Asia/Kolkata,2018-03-18,72.93924,excellent,IN,18.87813

In [4]:
stations.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1078 entries, 0 to 1077
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   location   1078 non-null   object
 1   revision   1078 non-null   object
 2   longitude  1078 non-null   float64
 3   QoS        1078 non-null   object
 4   code       1078 non-null   object
 5   latitude   1078 non-null   float64
dtypes: float64(2), object(4)
memory usage: 50.7+ KB

<h3>Uloha 2:

In [5]:

measurements[measurements.warning == 0].describe()

,PM10,NH3,warning,H2CO,SO2,TEMP,C2H3NO5,Pb,NOx,PM2.5,latitude,PRES,longitude,CH4,PAHs,CFCs,CO,O3
count,4878.000000,4871.000000,4893.0,4871.000000,4876.000000,4867.000000,4870.000000,4877.000000,4877.000000,4861.000000,4893.000000,4893.000000,4893.000000,4872.000000,4874.000000,4875.000000,4872.000000,4881.000000
mean,9.163642,6.695183,0.0,50.340709,7.973707,15.015414,0.581483,46.763519,7.943171,7.977579,27.059493,1124.972520,12.051498,7.998007,6.702391,48.331793,8.006819,7.993476
std,1.810498,1.365687,0.0,13.664003,1.785040,9.986942,2.664720,13.155566,1.990399,0.999091,24.014030,43.240166,73.957818,0.965478,1.271502,12.531152,1.923584,0.995766
min,1.922940,0.000000,0.0,0.000000,2.718990,-19.123330,0.011490,2.984400,0.978510,4.344390,-54.800000,1050.062060,-156.474320,4.544850,2.052640,0.000000,0.804270,3.775770
25%,7.996120,5.831835,0.0,41.563835,6.598907,8.296200,0.052003,38.059950,6.502890,7.319110,12.744090,1086.958190,-52.510280,7.340908,5.848130,40.288120,6.736223,7.335130
50%,9.166215,6.672690,0.0,50.453340,7.813435,14.784700,0.120565,46.670470,7.977890,7.966650,35.212220,1125.888430,9.150130,8.005435,6.677430,48.424820,8.293425,7.994650
75%,10.309567,7.579345,0.0,59.325265,9.285165,21.671440,0.333873,55.558880,9.423170,8.638500,44.852780,1161.900750,72.851070,8.657925,7.505675,56.762695,9.438523,8.672710
max,16.078750,12.253040,0.0,97.784900,14.354340,50.560240,100.000000,100.000000,14.261020,11.307140,68.798330,1199.967730,178.004170,11.640280,12.828690,100.000000,13.099800,11.201480

In [6]:
measurements[measurements.warning == 1].describe()

,PM10,NH3,warning,H2CO,SO2,TEMP,C2H3NO5,Pb,NOx,PM2.5,latitude,PRES,longitude,CH4,PAHs,CFCs,CO,O3
count,7127.000000,7131.000000,7160.0,7134.000000,7128.000000,7138.000000,7136.000000,7127.000000,7126.000000,7143.000000,7160.000000,7160.000000,7160.000000,7133.000000,7131.000000,7129.000000,7133.000000,7122.000000
mean,6.708200,6.643270,1.0,50.590466,9.257064,14.989498,0.046183,46.838360,6.678167,7.966125,27.146061,1124.328020,9.305330,7.954800,7.939603,48.033099,7.963104,7.973568
std,1.381827,1.413147,0.0,13.403088,1.155087,9.827542,0.081372,13.098414,1.560956,1.008257,23.831229,43.328045,74.740435,0.998448,1.829560,12.297186,1.802265,0.993988
min,0.480410,0.444820,1.0,2.436670,3.940400,-24.484960,0.000000,0.000000,0.781910,4.019010,-54.800000,1050.086940,-156.474320,4.277410,1.769110,6.627450,1.485110,4.212790
25%,5.800015,5.724335,1.0,41.381790,8.485183,8.352015,0.024770,37.807630,5.658865,7.281825,12.371690,1086.860782,-65.614270,7.286690,6.559830,39.496820,6.641810,7.308230
50%,6.694050,6.647780,1.0,50.349585,9.277475,15.083770,0.031070,46.724120,6.678520,7.971040,35.059665,1123.785435,8.770690,7.955520,7.767310,48.081480,8.025650,7.969780
75%,7.612215,7.550320,1.0,59.764888,10.036005,21.645665,0.043230,55.906815,7.701595,8.642260,43.914520,1161.929240,72.685330,8.630140,9.295950,56.203230,9.334520,8.629022
max,12.156610,12.527360,1.0,100.000000,12.864130,55.456920,1.993460,95.128740,13.312370,12.141360,68.798330,1199.979770,178.004170,11.939420,14.045020,91.432640,13.126980,11.541910